//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearcherInfoService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearcherAvailability
    {
        public int AvailabilityId { get; set; }
        public int ResearcherId { get; set; }
        public int Month { get; set; }
    
        public virtual User User { get; set; }
    }
}
